# Generated by Django 5.1.5 on 2026-02-12 05:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0014_alter_cheatingaudio_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('constraints', models.TextField(blank=True, null=True)),
                ('sample_input', models.TextField()),
                ('sample_output', models.TextField()),
                ('hidden_test_cases', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='cheatingaudio',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 12, 10, 35, 57, 174519)),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 12, 10, 35, 57, 173519)),
        ),
        migrations.AlterField(
            model_name='cheatingimage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 12, 10, 35, 57, 174519)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 12, 10, 35, 57, 172514)),
        ),
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 12, 10, 35, 57, 172514)),
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('output', models.TextField(blank=True, null=True)),
                ('passed_cases', models.IntegerField(default=0)),
                ('total_cases', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('coding_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='proctoring.codingquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score_mcq', models.IntegerField(default=0)),
                ('score_coding', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='proctoring.student')),
            ],
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='exam_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_questions', to='proctoring.examsession'),
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_option', models.CharField(max_length=1)),
                ('category', models.CharField(max_length=100)),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='proctoring.examsession')),
            ],
        ),
        migrations.CreateModel(
            name='ProctoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='proctoring.examsession')),
            ],
        ),
    ]
