# Generated by Django 5.1.5 on 2026-02-13 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0015_codingquestion_alter_cheatingaudio_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatingaudio',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 10, 21, 34, 739792)),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 10, 21, 34, 738793)),
        ),
        migrations.AlterField(
            model_name='cheatingimage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 10, 21, 34, 738793)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 10, 21, 34, 738793)),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='correct_option',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='selected_option',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 10, 21, 34, 737765)),
        ),
    ]
