# Generated by Django 5.1.5 on 2026-02-13 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0016_alter_cheatingaudio_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='difficulty',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='cheatingaudio',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 11, 1, 33, 435728)),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 11, 1, 33, 435728)),
        ),
        migrations.AlterField(
            model_name='cheatingimage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 11, 1, 33, 435728)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 11, 1, 33, 434725)),
        ),
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 11, 1, 33, 434725)),
        ),
    ]
