# Generated by Django 5.1.5 on 2026-02-13 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0018_alter_cheatingaudio_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatingaudio',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 16, 46, 17, 586582)),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 16, 46, 17, 586582)),
        ),
        migrations.AlterField(
            model_name='cheatingimage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 16, 46, 17, 586582)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 16, 46, 17, 585998)),
        ),
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 16, 46, 17, 584464)),
        ),
    ]
