# Generated by Django 5.1.5 on 2026-02-14 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0019_alter_cheatingaudio_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingsubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cheatingaudio',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 14, 57, 57, 297043)),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 14, 57, 57, 296041)),
        ),
        migrations.AlterField(
            model_name='cheatingimage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 14, 57, 57, 297043)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 14, 57, 57, 296041)),
        ),
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 14, 57, 57, 295041)),
        ),
    ]
