# Generated by Django 5.1.5 on 2026-03-09 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0020_codingsubmission_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingsubmission',
            name='coding_question',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='score_coding',
        ),
        migrations.AlterField(
            model_name='cheatingaudio',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 9, 11, 29, 43, 478453)),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 9, 11, 29, 43, 477546)),
        ),
        migrations.AlterField(
            model_name='cheatingimage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 9, 11, 29, 43, 477546)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 9, 11, 29, 43, 477025)),
        ),
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 9, 11, 29, 43, 476008)),
        ),
        migrations.DeleteModel(
            name='CodingQuestion',
        ),
        migrations.DeleteModel(
            name='CodingSubmission',
        ),
    ]
